Dim  Hablar, Discurso1, Discurso2
Discurso1="SE HA CREADO EL ARBOL DE DIRECTORIOS, Y LOS ARCHIVOS PRIMARIOS PARA DESARROLLO WEB"
Discurso2="RECUERDA REVISAR EL ARCHIVO INSTRUCCIONES PUNTO EME DE, PARA SABER QUE MODIFICACIONES TIENES QUE REALIZAR SOBRE LOS ARCHIVOS CREADOS"
Set Hablar=CreateObject("sapi.spvoice")
Hablar.Speak Discurso1
WScript.Sleep (100)
Hablar.Speak Discurso2
WScript.Sleep (500)